import OpenRouterService from './OpenRouterService';

// Define types for mindmap structure
export interface MindmapNode {
  id: string;
  topic: string;
  children: MindmapNode[];
  parentId?: string;
  depth: number;
}

export interface RawMindmapNode {
  topic: string;
  children: RawMindmapNode[];
}

class MindmapService {
  /**
   * Generate a mindmap from a given topic
   * @param topic The main topic for the mindmap
   * @param depth The depth of the mindmap
   * @returns The generated mindmap structure
   */
  async generateMindmap(topic: string, depth: number = 3): Promise<MindmapNode> {
    try {
      // Get raw mindmap data from AI
      const rawJson = await OpenRouterService.generateMindmap(topic, depth);
      
      // Parse and validate the JSON response
      const rawMindmap: RawMindmapNode = this.parseAndValidateMindmap(rawJson);
      
      // Convert to structured mindmap with IDs and depth information
      const structuredMindmap = this.convertToStructuredMindmap(rawMindmap);
      
      return structuredMindmap;
    } catch (error) {
      console.error('Error generating mindmap:', error);
      throw error;
    }
  }

  /**
   * Parse and validate the raw JSON mindmap response
   * @param rawJson The raw JSON string from the AI
   * @returns The parsed and validated mindmap
   */
  private parseAndValidateMindmap(rawJson: string): RawMindmapNode {
    try {
      // Clean the JSON string (remove any markdown formatting if present)
      const cleanedJson = this.cleanJsonString(rawJson);
      
      const parsed = JSON.parse(cleanedJson) as RawMindmapNode;
      
      // Validate the structure
      this.validateMindmapStructure(parsed);
      
      return parsed;
    } catch (error) {
      console.error('Error parsing mindmap JSON:', error);
      throw new Error('Invalid mindmap structure generated by AI');
    }
  }

  /**
   * Clean the JSON string by removing any extraneous characters
   * @param jsonString The raw JSON string
   * @returns The cleaned JSON string
   */
  private cleanJsonString(jsonString: string): string {
    // Remove markdown code blocks
    let cleaned = jsonString.replace(/^```json\n/, '').replace(/\n```$/, '');
    cleaned = cleaned.replace(/^```\n/, '').replace(/\n```$/, '');
    
    // Remove any leading/trailing whitespace
    cleaned = cleaned.trim();
    
    return cleaned;
  }

  /**
   * Validate the mindmap structure
   * @param mindmap The mindmap to validate
   */
  private validateMindmapStructure(mindmap: any): void {
    if (!mindmap || typeof mindmap !== 'object') {
      throw new Error('Mindmap must be an object');
    }
    
    if (!mindmap.topic || typeof mindmap.topic !== 'string') {
      throw new Error('Mindmap must have a topic string');
    }
    
    if (!Array.isArray(mindmap.children)) {
      throw new Error('Mindmap must have a children array');
    }
    
    // Validate all children recursively
    mindmap.children.forEach((child: any) => this.validateMindmapStructure(child));
  }

  /**
   * Convert raw mindmap to structured mindmap with IDs and depth
   * @param rawNode The raw mindmap node
   * @param parentId The parent ID (for recursive calls)
   * @param depth The current depth (for recursive calls)
   * @returns The structured mindmap node
   */
  private convertToStructuredMindmap(
    rawNode: RawMindmapNode,
    parentId?: string,
    depth: number = 0
  ): MindmapNode {
    const node: MindmapNode = {
      id: this.generateId(),
      topic: rawNode.topic,
      children: [],
      parentId,
      depth,
    };
    
    // Convert children recursively
    node.children = rawNode.children.map(child => 
      this.convertToStructuredMindmap(child, node.id, depth + 1)
    );
    
    return node;
  }

  /**
   * Generate a unique ID for mindmap nodes
   * @returns A unique ID
   */
  private generateId(): string {
    return Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
  }

  /**
   * Calculate the total number of nodes in the mindmap
   * @param mindmap The mindmap to count nodes for
   * @returns The total number of nodes
   */
  calculateNodeCount(mindmap: MindmapNode): number {
    let count = 1; // Count the current node
    
    // Count all children recursively
    for (const child of mindmap.children) {
      count += this.calculateNodeCount(child);
    }
    
    return count;
  }

  /**
   * Calculate the maximum depth of the mindmap
   * @param mindmap The mindmap to check
   * @returns The maximum depth
   */
  calculateMaxDepth(mindmap: MindmapNode): number {
    let maxDepth = mindmap.depth;
    
    // Check all children recursively
    for (const child of mindmap.children) {
      const childDepth = this.calculateMaxDepth(child);
      if (childDepth > maxDepth) {
        maxDepth = childDepth;
      }
    }
    
    return maxDepth;
  }
}

export default new MindmapService();
